#!/bin/sh
# WebUI icon used from http://icons8.com

DEVICE="HB-UNI-Sen-TEMP-DS18B20"
DEVICE_IMG=hb-uni-sen-temp-ds18b20.png
DEVICE_THUMB=hb-uni-sen-temp-ds18b20_thumb.png
FIRMWARE_FILE=/firmware/rftypes/hb-uni-sen-temp.xml

devdescrFile="/www/config/devdescr/DEVDB.tcl"
devdescrSearch="$DEVICE {{50 \/config\/img\/devices\/50\/$DEVICE_THUMB} {250 \/config\/img\/devices\/250\/$DEVICE_IMG}} "
sed -i "s/\($devdescrSearch\)//g" $devdescrFile

webuiFile="/www/webui/webui.js"
sed -i "/\($DEVICE\)/d" $webuiFile

webuiSearch="HBWEA_TRANSMIT_INTERVAL"
sed -i "/\($webuiSearch\)/d" $webuiFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB


stringtable_deFile="/www/config/stringtable_de.txt"

stringtable_deSearch="HBWEA_TRANSMIT_INTERVAL"
sed -i "/\($stringtable_deSearch\)/d" $stringtable_deFile

translate_deFile="/www/webui/js/lang/de/translate.lang.stringtable.js"

translate_deSearch="stringTableHbWeaTransmitInterval"
sed -i "/\(${translate_deSearch}\)/d" $translate_deFile

rm -f $FIRMWARE_FILE
rm -f /www/config/img/devices/250/$DEVICE_IMG
rm -f /www/config/img/devices/50/$DEVICE_THUMB
